### ISSUE TITLE
USER STORY: Favorite Recipes

### ISSUE THREAD

**Issue by siobhanlgorman** [siobhanlgorman/favoureats#11]
As a **registered user** I can **favorite/unfavorite recipes** so that **I can interact with the site content**

**Acceptance Criteria**:
-  1: Registered user can click on star icon in recipe detail post to favourite a recipe
-  2: Feature not available to non-registered users
-  3: User is redirected to recipe detail post

**Tasks**:
- [ ] Task 1: Create button for logged in users to click to favourite/unfavourite a recipe
- [ ] Task 2: Create recipe favourite view with post method
- [ ] Task 3: Redirect usere to post detail page after favouriting a recipe
