### ISSUE TITLE
USER STORY: View Recipe List page

### ISSUE THREAD

**Issue by siobhanlgorman** [siobhanlgorman/favoureats#15]
As a **user** I can **view a list of recipes with number of reviews and favourites** so that **I can see what I would like to select if registered**

**Acceptance Criteria**:
- 1: Recipes appear in list on recipes page
- 2: Number of reviews appears with recipe
- 3. Number of favourite stars appears with recipe

**Tasks**:
- [ ] Task 1: Add view code for recipes page
- [ ] Task 2: Add content to template
- [ ] Task 3: Wire up url
- [ ] Task 4: Add code for number of favourites and reviews
