### ISSUE TITLE
USER STORY: Register an Account

### ISSUE THREAD

**Issue by siobhanlgorman** [siobhanlgorman/favoureats#18]
As a **user** I can **register an account** so that **I can access the full range of features on the site**

**Acceptance Criteria**:
-  1: User can register an account
-  2: User details are visible in admin panel

**Tasks**:
- [ ] Task 1: Install allauth, 
- [ ] Task 2: Update requirements, urls 
- [ ] Task 3: Update settings
