### ISSUE TITLE
USER STORY: Login/Logout

### ISSUE THREAD

**Issue by siobhanlgorman** [siobhanlgorman/favoureats#19]
As a **registered user** I can **login and logout of the site** so that **I can access my content**

**Acceptance Criteria**:
-  1: User can login and logout of site
-  2: User is redirected to home page after login

**Tasks**:
- [ ] Task 1: Wire up login/logout links
- [ ] Task 2: Redirect to home page after login
- [ ] Task 3: Install and customise allauth account templates
