### ISSUE TITLE
USER STORY: View Full Recipe Post

### ISSUE THREAD

**Issue by siobhanlgorman** [siobhanlgorman/favoureats#20]
As a **registered user** I can **click on a post in the recipe list** so that **I open the full recipe post**

**Acceptance Criteria**:
-  1: User can open a post 

**Tasks**:
- [ ] Task 1: Create view
- [ ] Task 2: Create template
- [ ] Task 3: Connect urls
