### ISSUE TITLE
USER STORY: Search Own Recipe Posts

### ISSUE THREAD

**Issue by siobhanlgorman** [siobhanlgorman/favoureats#23]
As a **user** I can **search my own recipe posts by title and ingredient** so that **easily find a recipe**

**Acceptance Criteria**:
-  1: Logged in user can search for recipe by title

**Tasks**:
- [ ] Task 1: Create search bar
- [ ] Task 2: Connect search bar view
- [ ] Task 3: Set search fields
