### ISSUE TITLE
USER STORY: View Snapshot of Site

### ISSUE THREAD

**Issue by siobhanlgorman** [siobhanlgorman/favoureats#24]
As a **user** I can **view a snapshot of the site on the landing page** so that **know what the site's purpose is**

**Acceptance Criteria**:
-  1: Landing page completed

**Tasks**:
- [ ] Task 1: Create base.html template
- [ ] Task 2: Add HTML and CSS to landing page template
- [ ] Task 3: Add images to cloudinary
